#
# Copyright 2018 Delphix
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

---
#
# When using the APPLIANCE_PASSWORD variable, we have to be careful to
# specify "no_log" to prevent it from being leaked to stdout (e.g. if
# ansible is run with verbosity).
#
- fail:
    msg: "Required environment variable 'APPLIANCE_PASSWORD' is empty."
  when: lookup('env', 'APPLIANCE_PASSWORD') == ''
  no_log: true

- fail:
    msg: "Required environment variable 'APPLIANCE_USERNAME' is empty."
  when: lookup('env', 'APPLIANCE_USERNAME') == ''

#
# We use a non-standard directory for the appliance user's home
# directory. As a result, we have to explicitly create the "base
# directory" here, rather than rely on Ansible's user module to create
# it below; otherwise that task will fail.
#
- file:
    path: /export/home
    state: directory
    mode: 0755

#
# Finally, we need to configure our appliance user, such that we actually
# have a way to log into the system after it boots.
#
- user:
    name: "{{ lookup('env', 'APPLIANCE_USERNAME') }}"
    group: staff
    groups: root
    shell: /bin/bash
    create_home: yes
    comment: Delphix User
    home: "/export/home/{{ lookup('env', 'APPLIANCE_USERNAME') }}"
    password:
      "{{ lookup('env', 'APPLIANCE_PASSWORD') | password_hash('sha512') }}"

#
# While we create the user using Ansible, we need to inform cloud-init
# of this user so that SSH keys are properly inserted into this user's
# authorized_keys file (e.g. when running in EC2). Additionally, this
# will prevent cloud-init from creating the default user.
#
- copy:
    dest: /etc/cloud/cloud.cfg.d/99-delphix-user.cfg
    mode: 0644
    content: |
      system_info:
        default_user:
          name: {{ lookup('env', 'APPLIANCE_USERNAME') }}
          lock_passwd: false
